/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthDashboardSettingsRouteImport } from './routes/_auth/dashboard/settings'
import { Route as AuthDashboardApiKeysRouteImport } from './routes/_auth/dashboard/api-keys'
import { Route as AuthDashboardActivateRouteImport } from './routes/_auth/dashboard/activate'
import { Route as AuthDashboardDevicesIndexRouteImport } from './routes/_auth/dashboard/devices/index'
import { Route as AuthDashboardDevicesDeviceIdIndexRouteImport } from './routes/_auth/dashboard/devices/$deviceId/index'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardSettingsRoute = AuthDashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardApiKeysRoute = AuthDashboardApiKeysRouteImport.update({
  id: '/dashboard/api-keys',
  path: '/dashboard/api-keys',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardActivateRoute = AuthDashboardActivateRouteImport.update({
  id: '/dashboard/activate',
  path: '/dashboard/activate',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardDevicesIndexRoute =
  AuthDashboardDevicesIndexRouteImport.update({
    id: '/dashboard/devices/',
    path: '/dashboard/devices/',
    getParentRoute: () => AuthRoute,
  } as any)
const AuthDashboardDevicesDeviceIdIndexRoute =
  AuthDashboardDevicesDeviceIdIndexRouteImport.update({
    id: '/dashboard/devices/$deviceId/',
    path: '/dashboard/devices/$deviceId/',
    getParentRoute: () => AuthRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/activate': typeof AuthDashboardActivateRoute
  '/dashboard/api-keys': typeof AuthDashboardApiKeysRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/dashboard/devices/': typeof AuthDashboardDevicesIndexRoute
  '/dashboard/devices/$deviceId/': typeof AuthDashboardDevicesDeviceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/activate': typeof AuthDashboardActivateRoute
  '/dashboard/api-keys': typeof AuthDashboardApiKeysRoute
  '/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/dashboard/devices': typeof AuthDashboardDevicesIndexRoute
  '/dashboard/devices/$deviceId': typeof AuthDashboardDevicesDeviceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/dashboard/activate': typeof AuthDashboardActivateRoute
  '/_auth/dashboard/api-keys': typeof AuthDashboardApiKeysRoute
  '/_auth/dashboard/settings': typeof AuthDashboardSettingsRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/dashboard/devices/': typeof AuthDashboardDevicesIndexRoute
  '/_auth/dashboard/devices/$deviceId/': typeof AuthDashboardDevicesDeviceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/activate'
    | '/dashboard/api-keys'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/devices/'
    | '/dashboard/devices/$deviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/activate'
    | '/dashboard/api-keys'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/devices'
    | '/dashboard/devices/$deviceId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/dashboard/activate'
    | '/_auth/dashboard/api-keys'
    | '/_auth/dashboard/settings'
    | '/_auth/dashboard/'
    | '/_auth/dashboard/devices/'
    | '/_auth/dashboard/devices/$deviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/settings': {
      id: '/_auth/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthDashboardSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/api-keys': {
      id: '/_auth/dashboard/api-keys'
      path: '/dashboard/api-keys'
      fullPath: '/dashboard/api-keys'
      preLoaderRoute: typeof AuthDashboardApiKeysRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/activate': {
      id: '/_auth/dashboard/activate'
      path: '/dashboard/activate'
      fullPath: '/dashboard/activate'
      preLoaderRoute: typeof AuthDashboardActivateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/devices/': {
      id: '/_auth/dashboard/devices/'
      path: '/dashboard/devices'
      fullPath: '/dashboard/devices/'
      preLoaderRoute: typeof AuthDashboardDevicesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/devices/$deviceId/': {
      id: '/_auth/dashboard/devices/$deviceId/'
      path: '/dashboard/devices/$deviceId'
      fullPath: '/dashboard/devices/$deviceId/'
      preLoaderRoute: typeof AuthDashboardDevicesDeviceIdIndexRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthDashboardActivateRoute: typeof AuthDashboardActivateRoute
  AuthDashboardApiKeysRoute: typeof AuthDashboardApiKeysRoute
  AuthDashboardSettingsRoute: typeof AuthDashboardSettingsRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthDashboardDevicesIndexRoute: typeof AuthDashboardDevicesIndexRoute
  AuthDashboardDevicesDeviceIdIndexRoute: typeof AuthDashboardDevicesDeviceIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardActivateRoute: AuthDashboardActivateRoute,
  AuthDashboardApiKeysRoute: AuthDashboardApiKeysRoute,
  AuthDashboardSettingsRoute: AuthDashboardSettingsRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthDashboardDevicesIndexRoute: AuthDashboardDevicesIndexRoute,
  AuthDashboardDevicesDeviceIdIndexRoute:
    AuthDashboardDevicesDeviceIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
