name: Extract Keystore Secrets

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Output secrets as b64 artifacts
        run: |
          echo "$KEY_ALIAS" | base64 > /tmp/key_alias_b64.txt
          echo "$KEY_PASSWORD" | base64 > /tmp/key_password_b64.txt
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload secrets
        uses: actions/upload-artifact@v4
        with:
          name: keystore-secrets-2
          path: /tmp/key_*.txt
          retention-days: 1
